# -*- mode:python -*-

Import('*')

DebugFlag('AVR')
DebugFlag('AVRInst')
DebugFlag('AVRDecoder')

Source('utility.cc')
Source('registers.cc')
Source('faults.cc')
Source('isa.cc')


SimObject('AVR.py', sim_objects=['AVR'])

# Generate ISA decoder
isa_desc = ISADesc('isa/main.isa')
